#sdk: "/opt/local/lib/ruby/gems/1.8/gems/rhodes-3.3.3"
sdkversion: 3.3.3
name: form_elements
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator4.3
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.formelements
  BundleURLScheme: formelements
wp:
  productid: '928df0e0-8f73-012f-2d22-60c54789b794'
symbian:
  uid: '0xefbc6836'
android:
  version: 2.3.3

extensions: ["json", "another-extension"]
